name: first-workflow
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World"
      - name: second-step
        run:  |
            echo "Done goodbye1"
            echo "Done goodbye2"
